### ISSUE TITLE
Use fine grained sudo permissions

### ISSUE THREAD

**Issue by eschrock** [delphix/ansible-target-host#1]
The role currently configures fairly permissive sudo permissions, with full access to any of the command set.  For example, the [Oracle documentation](https://docs.delphix.com/docs/delphix-administration/oracle-environments-and-data-sources/oracle-support-and-requirements/sudo-file-configuration-examples-for-oracle-environments) gives the following example:

```
Defaults:delphix_os !requiretty
delphix_os ALL=(root) NOPASSWD: \
/bin/mount  *        /oracle/*, \
/bin/umount *        /oracle/*, \
/bin/umount          /oracle/*, \
/bin/umount -lf      /oracle/*, \
/bin/ps
```

We could use these more restrictive permissions to only allow mounts within the delphix mount point, for example.

**Comment by CloudSurgeon** [comment]
The user is provided a configurable variable to override the default sudoer provileges in 78fea468e97da18c06e78b7d9494c9f7748127ab
